spring:
  application:
    name: project-management-app
  datasource:
    url: jdbc:postgresql://localhost:5432/project_management_app
    username: project_management_app
    password: project_management_app
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

projectmanagementapp:
  cors:
    allowed-origins:
      - http://localhost:5173
