spring:
  application:
    name: project-management-app
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres?currentSchema=management_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.projectmanagementapp.domain.model
  configuration:
    map-underscore-to-camel-case: true

projectmanagementapp:
  cors:
    allowed-origins:
      - http://localhost:5173
